### PR TITLE
Add instructions to inspect the Blobstore contents using mc

### PR DESCRIPTION
**Pull request by krishnasrinivas**

### CODE REVIEW

**Comment by jncd** [comment]
I merged, edited and restaged.
Don't forget to use https://github.com/pivotal-cf/docs-partners-template/blob/master/style-guide.md

**Comment by krishnasrinivas** [comment]
https://minio-internal-blobstore-162142678.cfapps.io/minio-internal-blobstore/operator-guide.html#inspect

@jncd your changes https://github.com/pivotal-cf/docs-minio-internal-blobstore/commit/416675b00e5f40ded5c89e28de11f39039fdf3c7 makes it look like this (check the formatting of the commands):

wrong-inspect

Without it, it looks correct, like this:
right-inspect

Can you fix your changes?

**Comment by jncd** [comment]
Thanks, yes, I can make those changes. 
I'll try to do it right this time. (Does Minio have any tech writers in-house?)

**Comment by krishnasrinivas** [comment]
> I'll try to do it right this time. (Does Minio have any tech writers in-house?)

Yes, there is a new tech writer who is getting up to speed

**Comment by krishnasrinivas** [comment]
> Thanks, yes, I can make those changes.

I tried to fix it, but could not figure it out.

**Comment by jncd** [comment]
I used the template here to format the commands. https://docs-wiki.cfapps.io/wiki/style/documenting-commands.html
(You can add the examples and define the variables.)

**Comment by krishnasrinivas** [comment]
Ah, thanks for the link

**Pull request merged**
